global:
  scrape_interval: 15s  # How often to scrape targets (default is 1m)
  evaluation_interval: 15s  # How often to evaluate rules (default is 1m)

  # Scrape timeout
  scrape_timeout: 10s

  # Optional: Enable/disable the "prometheus" job by default
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  # Scraping Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrape Prometheus itself

  # Scrape Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Change to your node-exporter host if necessary

  # Scrape the linux-container
  - job_name: 'linux-container'
    static_configs:
      - targets: ['linux-container:8080']  # Ensure the linux-container exposes a /metrics endpoint

  # Scrape cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Scrape cAdvisor metrics from the cAdvisor container (port 8080)

  # Example for other services like blackbox or MySQL Exporter
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql-exporter:9104']

  # Scrape a custom service, e.g., HTTP API
  # - job_name: 'my-service'
